inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - tmp/**/*
    - vendor/**/*
    - test/fixtures/**/*
    - test/functions.rb

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Gemspec/DevelopmentDependencies:
  Enabled: false
