name: Lock inactive closed threads

on:
  schedule:
    - cron: '23 7 * * 1'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock-threads

jobs:
  lock-threads:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: Lock inactive closed threads
        uses: dessant/lock-threads@89ae32b08ed1a541efecbab17912962a5e38981c # v6
        with:
          issue-inactive-days: '90'
          issue-comment: ''
          issue-lock-reason: resolved
          add-issue-labels: ''
          remove-issue-labels: ''
          pr-inactive-days: '30'
          pr-comment: ''
          pr-lock-reason: resolved
          add-pr-labels: ''
          remove-pr-labels: ''
          process-only: "issues, prs"
          log-output: true

